export const SCREENS = {
  WELCOME: 'Welcome',
  HOME: 'Home',
  MENU: 'Menu',
  CART: 'Cart',
  POPULAR_PRODUCTS: 'PopularProducts',
  PROFILE: 'Profile',
  COFFEE_DETAILS: 'CoffeeDetails',
  CHECKOUT: 'Checkout',
  CATEGORY_PRODUCTS: 'CategoryProducts',
  FAVORITES: 'Favorites',
  SETTINGS: 'Settings',
  ABOUT: 'About',
  CONTACT: 'Contact',
};